# Generated by Django 2.2.4 on 2023-10-12 10:19

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=10, null=True)),
                ('firstname', models.CharField(db_column='firstName', max_length=16)),
                ('lastname', models.CharField(blank=True, db_column='lastname', max_length=16, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('N', 'N')], db_column='gender', max_length=1, null=True)),
                ('is_active', models.CharField(choices=[('A', 'A'), ('I', 'I')], db_column='isActive', default='A', max_length=1)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('roles', jsonfield.fields.JSONField(db_column='roles', default=[])),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
