# Generated by Django 2.2.4 on 2023-11-02 06:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_customuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=jsonfield.fields.JSONField(db_column='roles', default=['endUser']),
        ),
    ]
