# Generated by Django 2.2.4 on 2023-10-13 05:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('category_name', models.CharField(db_column='categoryName', max_length=16, unique=True)),
                ('category_desc', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('todo_name', models.CharField(db_column='todoName', max_length=56)),
                ('desc', models.TextField(blank=True, db_column='description', null=True)),
                ('is_important', models.BooleanField(db_column='isImportant', default=False)),
                ('due_date', models.DateField(blank=True, db_column='dueDate', null=True)),
                ('completed', models.BooleanField(db_column='completed', default=False)),
                ('note', models.TextField(blank=True, db_column='note', null=True)),
                ('cateid', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_cateid', to='todomanagement.Category')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='todo_userid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Todos',
            },
        ),
        migrations.CreateModel(
            name='TodoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, db_column='FilePath', max_length=200, null=True)),
                ('todo', models.ForeignKey(db_column='todoId', on_delete=django.db.models.deletion.CASCADE, related_name='todoimage_todoid', to='todomanagement.Todos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(db_column='todoId', on_delete=django.db.models.deletion.CASCADE, related_name='myday_todoid', to='todomanagement.Todos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
