# Generated by Django 2.2.4 on 2023-11-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomanagement', '0003_todos_todo_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todos',
            unique_together={('todo_date', 'todo_name')},
        ),
    ]
