# Generated by Django 2.2.4 on 2023-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanagement', '0004_auto_20231101_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todo_date',
            field=models.DateField(blank=True, db_column='todoDate', null=True),
        ),
    ]
