# Generated by Django 2.2.4 on 2023-11-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomanagement', '0005_auto_20231102_0628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todos',
            unique_together=set(),
        ),
    ]
