# Generated by Django 3.2.23 on 2023-11-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanagement', '0007_alter_todoimages_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoimages',
            name='created_by',
            field=models.CharField(db_column='createdBy', default=None, max_length=16),
            preserve_default=False,
        ),
    ]
