# Generated by Django 3.2.23 on 2023-11-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanagement', '0008_todoimages_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoimages',
            name='file_path',
            field=models.FileField(blank=True, db_column='FilePath', null=True, upload_to='files/'),
        ),
    ]
